### ISSUE TITLE
A confirmation dialog is displayed after loading an annotation without modifying it.

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#87] opened 2019-06-01 15:30 UTC
**Description**
A confirmation dialog is displayed after loading an annotation without modifying it.

**Expected behavior**
User shouldn't be presented with a confirmation dialog 

**How to Reproduce**

1. Start the application
2. Then load an annotation
3. Close the application
4. A confirmation dialog appear

**Comment by wbwakeman** [comment] 2021-07-29 01:08
Duplicate of #111 ?

**Comment by allemangD** [comment] 2021-07-29 14:38
I agree; this is just a special case of #111 when the scene is empty. Closing.

**Closed by allemangD** 2021-07-29 14:38 UTC
Labels: Category: Usability, Type: Enhancement
