### ISSUE TITLE
Ability to Delete Whole Polygons

### ISSUE THREAD

**Issue by joshusama** [BICCN/cell-locator#114] opened 2020-05-13 16:11 UTC
**What's the problem this feature will solve?**
This will allow one to start over in a drawing more simply than deleting a file and creating new (which transports to the default location)

**Describe the solution you'd like**
A right-click option where you can elect to delete polygon

I draw a polygon that has many suboptimal nodes or curves.  Rather than deleting all the nodes to erase the polygon, it would be nice to allow me to remove the whole polygon with one click.  

**Alternative Solutions**
 1. delete all nodes to start over
 2. close file, delete file from list of files, open new, find location, set angle, redraw

Both alternative solutions can take significant time and/or add to ergonomic burden

HIGH PRIORITY

**Comment by wbwakeman** [comment] 2020-06-03 01:13
Duplicate of #102

**Comment by jcfr** [comment] 2020-08-27 18:54
Closing. Duplicate

**Closed by jcfr** 2020-08-27 18:54 UTC
Labels: Size: S, Status: Triage
