### ISSUE TITLE
User draw annotation on left, it appear on right in 3D

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#101] opened 2020-04-09 19:52 UTC
**Description**

Reported  by @wbwakeman

When users draw an annotation in the Slice viewer on the left,  it appears on the right in 3D.

![image](https://user-images.githubusercontent.com/219043/78935007-f055ae80-7a79-11ea-8085-0585ef65a416.png)

**Expected behavior**

Annotation should appear on the left

**Comment by jcfr** [comment] 2020-04-16 17:55
Related to #74 (ReferenceView: Select sagittal -> 2D and 3D view have different orientation)

**Comment by jcfr** [comment] 2020-04-16 18:12
Annotation now appears at the expected location:

![image](https://user-images.githubusercontent.com/219043/79491289-39fb4780-7fec-11ea-84bb-e15c355fa009.png)

**Comment by deenick** [comment] 2020-04-17 18:48
@jcfr Thanks for making this change.  The current view as currently stands means that users need to draw on right side of 2D image for a Left Hemisphere annotation on 3D image.  Is it possible to flip 3D image so right is right and left is left?  This would minimize errors/confusion I believe.

**Comment by jcfr** [comment] 2020-04-23 10:20
Based on the following description of the atlas (available [here](https://help.brain-map.org/display/mousebrain/API#API-DownloadAtlas3-DReferenceModels)), I looks like the right side is shown on the right.

![](https://user-images.githubusercontent.com/1854389/49306633-a45b2880-f487-11e8-95ee-b97bbf23a4f9.png) 

Copied from issue https://github.com/BICCN/cell-locator/issues/48

**Comment by wbwakeman** [comment] 2020-04-23 15:11
I think the point that Nick is trying to make is that the coronal views of the brain in the Cell Locator tool are shown as if we are looking at the front of the brain, like "face-to-face" with the mouse.  If both views were rotated so that we were looking at the back of the brain, then when a tool user draws something in the "right" side of the picture, that is going in the "right" side of the brain (and vice versa). 

I can imagine Nick's concern is that a user who has to think "I'm drawing a polygon in the right hemisphere, so therefore I need to draw it on the left side of this image" is going to make mistakes.

**Comment by jcfr** [comment] 2020-04-23 16:31
After further analysis,  the problem has been identified and fix is being along side new installer will be published shortly.

It is important to get this right so that we can finalize the LIMS integration

**Comment by deenick** [comment] 2020-04-23 16:46
Thanks for providing a better explanation Wayne.  I think resolving that will reduce errors when drawing.

**Comment by jcfr** [comment] 2020-04-23 18:52
After further analysis, part of the fix for #48 implemented in 49425f929a148a was incorrect.

Commit 2910414  revisits the approach and ensures the right part of the viewer is the right part of the brain.

![image](https://user-images.githubusercontent.com/219043/80137826-dc2da900-8571-11ea-9ef4-a41870c4c75a.png)

**Comment by jcfr** [comment] 2020-04-30 17:43
@deenick The installer available here should address the problem, see https://github.com/BICCN/cell-locator/releases/tag/0.1.0-2020-04-30

**Comment by deenick** [comment] 2020-04-30 19:06
@jcfr I just downloaded 4.30 version using the installer link above.  I do not recognize the user interface with this new version, it appears completely different.  Unable to figure out how to see slicer or draw polygons as done with previous versions.

**Comment by jcfr** [comment] 2020-04-30 19:35
> https://github.com/BICCN/cell-locator/commit/25c8d6b51ab32a9d2bed43731acebe787a4b0059

Could you share a screenshot ?

**Comment by jcfr** [comment] 2020-04-30 19:39
Also you could right click somewhere near the top of the application, and show the python interactor. Is there any information displayed there ? 

![image](https://user-images.githubusercontent.com/219043/80751989-c4699e00-8af8-11ea-86a5-492d721cfc8a.png)

**Comment by jcfr** [comment] 2020-04-30 19:43
Here is the issue:

![image](https://user-images.githubusercontent.com/219043/80752244-2de9ac80-8af9-11ea-88ce-ad56837a45ea.png)

Note  all dependencies have been updated while building the project. I will address this and also add a testing step in the release process to prevent future regression like this one.

Please, wait to hear back from me.

**Comment by deenick** [comment] 2020-04-30 21:19
When first opens:
![image](https://user-images.githubusercontent.com/26012915/80760363-a0ed2600-8aed-11ea-80cb-8137e4612310.png)

**Comment by deenick** [comment] 2020-04-30 21:20
After selecting all options for module panel:
![image](https://user-images.githubusercontent.com/26012915/80760419-bbbf9a80-8aed-11ea-9e49-419177d6c980.png)

**Comment by jcfr** [comment] 2020-04-30 23:03
@wbwakeman  @deenick  The installer has been fixed. Consider re-downloading from https://github.com/BICCN/cell-locator/releases/tag/0.1.0-2020-04-30

**Comment by deenick** [comment] 2020-04-30 23:08
Thanks @jcfr!  I just downloaded and looks good at first pass.  Both views are same so left is left.  This small change will be very helpful for my team to annotate dissections

**Comment by jcfr** [comment] 2020-04-30 23:25
Thanks for the update, but while working on documenting the meaning of raw/pitch/yaw, I realized that there is still something off. 

If you rotate the volume to match the orientation of 

![](https://help.brain-map.org/download/attachments/5308472/3DOrientation.png?version=1&modificationDate=1368132564812&api=v2)

Available at https://help.brain-map.org/display/mousebrain/API#API-InformaticsDataProcessing

where S is P and I is V, you can see that the the dataset is not properly oriented.

**Comment by jcfr** [comment] 2020-04-30 23:27
I will have an other look at the header  information in the nrrd file, as I discussed in the past with David, the info are incorrect .. see https://github.com/BICCN/cell-locator/issues/48#issue-386294514

**Comment by wbwakeman** [comment] 2020-05-01 16:47
@jcfr  I just tried this on the release from yesterday and it doesn't actually seem to work.  Here is a screenshot of my drawing on the left side.
![image](https://user-images.githubusercontent.com/1855315/80823069-bd8e6a00-8b90-11ea-966d-ce17a9f4b3ff.png)

**Comment by deenick** [comment] 2020-05-01 16:51
@wbwakeman It works as expected for me
![image](https://user-images.githubusercontent.com/26012915/80823351-545b2680-8b91-11ea-8be1-f0b00a763063.png)

**Comment by wbwakeman** [comment] 2020-05-01 16:53
Thanks @deenick . I'll try again, double-checking that I am not doing something silly

**Comment by wbwakeman** [comment] 2020-05-01 16:57
I think it was because I had started by loading one of your teams 10X annotations.  Then I started a new drawing but the view was still reversed.  So that is something to take note of.  Although the location of the annotations that your team has already done are in the correct hemisphere, the view in the left pane still appears as reversed.

**Comment by deenick** [comment] 2020-05-01 16:59
@wbwakeman Correct.  I had my team load in old jsons and they said the view on right flips back and is reversed when viewing drawings made using previous version.

**Comment by wbwakeman** [comment] 2021-07-29 01:03
I'm thinking this one can be closed now.  What do you think @jcfr ?

**Comment by allemangD** [comment] 2021-07-29 14:47
I agree. I'm not able to reproduce; this should have been fixed by #51 and #168; and integrating @lydiang's work in [Fixing direction and spacing in CCF volume files.ipynb](https://github.com/AllenInstitute/atlas_helper_tools/blob/main/fix_ccf_orientation/Fixing%20direction%20and%20spacing%20in%20CCF%20volume%20files.ipynb) will supersede this anyway. Closing.

**Closed by allemangD** 2021-07-29 14:47 UTC
Labels: Type: Bug, qa: biccn
