### ISSUE TITLE
Data Tracking

### ISSUE THREAD

**Issue by aleonlein** [BICCN/cell-locator#95] opened 2019-10-23 20:17 UTC
**What's the problem this feature will solve?**

 I am trying to understand what data is being sent back from the cell locator after a user is finished pinning. I also need to know what/if any information will need to be sent to the cell locator upon start up or before pinning. 

The program I am writing will open up the cell-locator after a user is finished acquiring data on a cell and my app is responsible, for now, for getting the information from the pinning tool to our LIMS team. 

**Describe the solution you'd like**
 

Description of output data from cell-locator as well as a description of what input is required.

**Alternative Solutions**

**Additional context**

**Comment by jcfr** [comment] 2020-09-12 03:53
Closing. Duplicate of #93 

cc: @wbwakeman

**Closed by jcfr** 2020-09-12 03:53 UTC
Labels: Status: No Action
